# 配置
title: 小恐龙 #标题
subtitle: 年轻人的IT启蒙者 #副标题
description:  小恐龙教育致力于启蒙年轻人的IT中国梦 #描述
keywords: 小恐龙教育,小恐龙,教育,IT,游戏,PS #关键字
author: 站长小钢蛋 #作者
language: zh-Hans #语言

# 分页
menu:
  主页: / #主页
  分类: /category #分类
  最近: /recent #最近
  关于: /about #关于

# 网站图标
favicon: /images/favicon.jpg
logo: /images/logo.png

# 上方展示图片
loading: /images/img_load1.jpg
header_home_image: /images/home_img1.jpg
header_category_image: /images/home_img2.jpg
header_recent_image: /images/home_img3.jpg
header_about_image: 